site_name: Orchid
site_url: https://docs.orchid.com/
use_directory_urls: true

theme:
  name: readthedocs

nav:

    - Home: 'index.md'
    - Orchid Accounts: 'accounts.md'
    - The Orchid Client: 'using-orchid.md'
    - The Orchid DApp: 'orchid-dapp.md'
    - FAQ: 'faq.md'
