name: orchid
description: Orchid Dapp Widget
version: 1.0.0

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cupertino_icons: 1.0.2
  dartjsengine: 1.0.1
  ethereum_address: 1.0.1 # for EIP-55
  flutter:
    sdk: flutter
  flutter_cupertino_localizations: 1.0.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: 0.19.3
  http: 0.12.2 # XXX: web3dart
  intl: 0.17.0
  rxdart: 0.25.0
  shared_preferences: 2.0.5
  styled_text: 4.0.0
  url_launcher: 6.0.3
  uuid: 2.2.2 # XXX: web3dart
  web3dart: 1.2.3
  flutter_web3: 2.1.6
  flutter_lints: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: 1.11.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/svg/chains/

flutter_intl:
  enabled: true

