name: CI
on: [push]
jobs:

  build-and-app:
    runs-on: ubuntu-latest

    steps:
    - name: rm -rf /opt
      run: sudo rm -rf /opt

    - name: install NDK r22
      run: echo y | sudo -EH "${ANDROID_HOME}/tools/bin/sdkmanager" "ndk;22.1.7171670" >/dev/null

    - uses: actions/checkout@v2
    - name: env/setup
      run: env/setup.sh
    - name: git submodule status
      id: git-submodule-status
      run: echo "::set-output name=hash::$(git submodule status | sed -e 's/^.\([^ ]*\) \([^ ]*\).*/\2 \1/' | LANG=C sort | openssl sha1 -binary | xxd -p -c20)"
    - uses: actions/cache@v2
      with:
        path: .git/modules
        key: git-modules-${{ steps.git-submodule-status.outputs.hash }}
    - name: git submodule
      run: env/submodule.sh --jobs 3

    - name: make Android .apk
      run: ANDROID_NDK_HOME=${ANDROID_HOME}/ndk/22.1.7171670 make -j3 -C app-android precache='--no-ios'
    - uses: actions/upload-artifact@v1
      with:
        name: orchid-apk
        path: app-android/out-and/Orchid.apk
