name: CI
on: [push]
jobs:

  build-mac-snd:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - run: env/setup.sh
    - uses: ./.github/actions/submodule

    - run: make -j3 -C eth-sender

    - uses: actions/upload-artifact@v1
      with:
        name: cj-mac
        path: eth-sender/out-mac/x86_64/cj
